name: zojatech
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  # State management
  get_it: ^7.6.4
  get: ^4.6.6
  provider: ^6.1.1

  # Utils
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^2.0.10+1

  # local DB
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2


 


  # connectivity
  http: ^1.1.0
  http_parser: ^4.0.2
  permission_handler: ^10.2.0
  diox: ^5.0.0
  logger: ^2.0.2+1
 

  #functionalities
  intl: ^0.18.1
  rename_app: ^1.5.0
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  loader_overlay: ^4.0.0
  
  
  

  #loading effect
  redacted: ^1.0.11
  
  #toast
  toastification: ^2.0.0
  flutter_locales: ^3.0.1
  sqflite: ^2.3.3+1
  smooth_page_indicator: ^1.2.0+3
  go_router: ^14.2.3

 


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/mobile/
    - assets/svg/
   
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf

       
