import '../../res/import/import.dart';

/// constant colors
const Color zojatechTransparent = Colors.transparent;
const Color zojatechBlack = Colors.black;
const Color zojatechRed = Colors.red;
const Color zojatechGrey = Color(0xff98A2B3);
const Color zojatechWhite = Colors.white;
const Color zojatechGreen = Colors.green;
const Color zojatechBackgroundColor = Color(0xffFEFEFE);

const Color zojatechPrimaryColor = Color(0xff6ABA51);
const Color zojatechSecondaryColor = Color(0xffFFC300);
const Color zojatechTertiaryColor = Color(0xffF4D0D9);
const Color zojatechTextColor = Color(0xff1E1E1E);
const Color zojatechHintTextColor = Color(0xff1E1E1E);
const Color zojatechFillColor = Color(0xffF9FAFB);
const Color zojatechSubColor = Color(0xffFEFEFE);
const Color zojatechPopUpGreyColor = Color(0xff141414);
const Color zojatechWhiteToBlackColor = Color(0xffCCCCCC);
const Color zojatechSubColor1 = Color(0xff999999);
const Color zojatechDeactivatedGrey = Color(0xffBBB5AC);
const Color zojatechGetOTPColor = Color(0xffF5F4FF);
const Color zojatechCountryColor = Color(0xff667085);
const Color zojatechTierColor = Color(0xffEBF2FF);
const Color zojatechCurrencyDropColor = Color(0xffCFF1FF);
const Color zojatechPurpleColor = Color(0xff9A4AFF);
const Color zojatechDividerColor = Color(0xffCCCCD0);
const Color zojatechSplashColor = Color(0xffF0F8EE);
const Color zojatechColor1 = Color(0xff666666);
const Color zojatechColor2 = Color(0xff0F0F0F);
const Color zojatechColor3 = Color(0xff1A1A1A);
const Color zojatechColor4 = Color(0xffE4ECE2);
const Color zojatechColor5 = Color(0xff023E4F);
const Color zojatechColor6 = Color(0xffF2F2F2);
const Color zojatechColor7 = Color(0xffEFFFF0);
const Color zojatechColor8 = Color(0xffD0D5DD);
const Color zojatechColor9 = Color(0xffEE6639);
const Color zojatechColor10 = Color(0xffF1636A);
const Color zojatechColor11 = Color(0xff0170A6);
const Color zojatechColor12 = Color(0xffD1EAC9);
const Color zojatechColor13 = Color(0xffF5F7FC);
const Color zojatechColor14 = Color(0xff076E87);
const Color zojatechColor15 = Color(0xffB8D7E6);
